"""update date column in company

Revision ID: 826a87eeeb82
Revises: 4d921b3efa8c
Create Date: 2023-08-31 14:29:42.252481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826a87eeeb82'
down_revision = '4d921b3efa8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_opened', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('date_opened')

    # ### end Alembic commands ###
